### ISSUE TITLE
Make iconv requirement optional

### ISSUE THREAD

**Issue by webmozart** [hoaproject/Ustring#31]
I'm currently looking at integrating hoa/console into the [webmozart/console](/webmozart/console) library. However, hoa/console depends on hoa/ustring, which in turns requires the iconv extension to be installed.

Does this really have to be a hard requirement instead of a suggest? As far as I saw, iconv is only needed for `Ustring::transcode()`. You could check whether the function is available there, throw an exception otherwise and add iconv to "suggest" instead. I'd be happy about reduced dependencies.

**Comment by Hywan** [comment]
Hello :-),

Good news!
Yes it is possible. I will fix it as soon as possible. The same way `ext/mbstring` is suggested, `ext/iconv` must be suggested too, you're right.

**Comment by webmozart** [comment]
Great, thanks! :)

**Comment by jubianchi** [comment]
:+1:

**Comment by Hywan** [comment]
I won't be able to do that today, maybe this weekend or Monday for sure!

**Comment by Hywan** [comment]
@webmozart Normally, we have to wait 6 weeks before the next snapshot (“release”/tag). We don't create a new snapshot because it's not a bug fix (please see http://hoa-project.net/Source.html#Rush_Release). However, we can do an exception, it's not a hard rule (since we have rolling release, we don't really care about tags :wink:). The question is: Do you need a new snapshot yet or can you wait approximately 6 weeks?

**Comment by Hywan** [comment]
@webmozart Finally I created a new snapshot since we can consider the `ext/mbstring` global check as a bug fix. So here is the https://github.com/hoaproject/Ustring/releases/tag/3.15.08.03 :smile:. Happy coding!

**Comment by webmozart** [comment]
Wow, that's some service! Thanks :)
